apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-deployment
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservice
  template:
    metadata:
      labels:
        app: microservice
    spec:
      containers:
      - name: microservice-container
        image: asm789/microservice-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: microservice-service
  namespace: myapp
spec:
  type: NodePort
  selector:
    app: microservice
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
